notifications:
  email: false

code: &code
  stage: "Code"
  dist: xenial
  language: python
  cache: pip
  sudo:
    false
  install:
    - sudo apt-get install -y gir1.2-gstreamer-1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libcairo2-dev libgirepository1.0-dev
    - pip install -e ".[test]"
  script:
    - pytest
  after_success:
    - pip install coveralls
    - coveralls

matrix:
  include:
    - <<: *code
      name: "Python 3.5"
      python: 3.5
    - <<: *code
      name: "Python 3.6"
      python: 3.6
    - <<: *code
      name: "Python 3.7"
      python: 3.7
    - <<: *code
      name: "Python 3.8"
      python: 3.8
